# Database
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
spring:
    datasource:
        url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
        username: ${DATABASE_USERNAME}
        password: ${DATABASE_PASSWORD}
    jpa:
        hibernate:
            ddl-auto: ${DATABASE_DDL}
        properties:
            hibernate:
                format_sql: true
        show-sql: true

# Swagger
springfox:
    documentation:
        swagger:
            v2:
                path: /documentation/swagger