# Database
logging:
    level:
        org:
            hibernate:
                type:
                    descriptor:
                        sql: trace
spring:
    datasource:
        password: 1
        url: jdbc:postgresql://localhost:5432/tablebooking
        username: postgres
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                format_sql: true
        show-sql: true
